# Generated by Django 3.1.7 on 2021-03-30 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1, unique=True, verbose_name='单字')),
                ('element', models.CharField(blank=True, max_length=1, null=True, verbose_name='五行')),
                ('pinyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='拼音')),
                ('tone', models.CharField(blank=True, max_length=50, null=True, verbose_name='声调')),
                ('meaning', models.CharField(blank=True, max_length=255, null=True, verbose_name='字义')),
                ('idiom', models.CharField(blank=True, max_length=100, null=True, verbose_name='成语')),
                ('poetry', models.CharField(blank=True, max_length=255, null=True, verbose_name='诗词')),
                ('provenance', models.CharField(blank=True, max_length=100, null=True, verbose_name='出处')),
                ('custom_meaning', models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字义')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='删除')),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'word',
            },
        ),
    ]
