# Generated by Django 3.1.7 on 2021-04-03 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True, verbose_name='单字')),
                ('element', models.CharField(blank=True, max_length=1, null=True, verbose_name='五行')),
                ('pinyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='拼音')),
                ('tone', models.CharField(blank=True, max_length=50, null=True, verbose_name='声调')),
                ('provenance', models.CharField(blank=True, max_length=100, null=True, verbose_name='出处')),
                ('moral', models.CharField(blank=True, max_length=255, null=True, verbose_name='寓意')),
                ('sex', models.CharField(blank=True, max_length=1, null=True, verbose_name='性别')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='删除')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'name',
            },
        ),
        migrations.AddField(
            model_name='word',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='声母'),
        ),
        migrations.AddField(
            model_name='word',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='性别'),
        ),
    ]
